//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireLow
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int REFID { get; set; }
        public string APPELLATION { get; set; }
        public string CNAME { get; set; }
        public string CTAXNO { get; set; }
        public string CTAXOFFICE { get; set; }
        public string CGSM { get; set; }
        public string CMAIL { get; set; }
        public string CPROVINCE { get; set; }
        public string CDISTRICT { get; set; }
        public string CADRESS { get; set; }
        public string CAREA { get; set; }
        public Nullable<int> CSTATUS { get; set; }
    }
}
